baseURL = "https://ivoszbg.github.io/"
languageCode = 'en-us'
title = 'Ivaylo Ivanov'
theme = 'typo'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[params]
description = "Ivaylo's Blog"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a 17 years old embedded developer from Bulgaria, stuyding in 11th grade with software and hardware at PPMG “Geo Milev”. At night, I'm working on bringing support for modern Samsung and Qualcomm SoCs in the mainline Linux kernel.

See ya at 🐧[linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/?qt=author&q=Ivaylo+Ivanov)!
"""

# Collection to display on home
homeCollectionTitle = 'Blogs'
homeCollection = 'blog'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ivaylo-ivanov-ivanov1/"

[[params.social]]
name = "github"
url = "https://github.com/ivoszbg"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blogs"
url = "/blog"

[[params.menu]]
name = "achievements"
url = "/portfolio"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
